import globals from 'globals'
import pluginJs from '@eslint/js'

export default [
  {
    languageOptions: {globals: {...globals.browser, process: true}},
    ignores: [
      '**/*.d.ts',
      'emsdk/**/*',
      'node_modules/**/*',
      'coverage/**/*',
      'dist/**/*',
      '**/*.min.js',
      'public/js/src/**/*',
      'tools/scripts/validate-github-pages.js'
    ]
  },
  pluginJs.configs.recommended,
  {
    files: ['public/src/**/*.js'],
    rules: {
      'array-callback-return': 'error',
      'arrow-body-style': 'error',
      camelcase: ['error', {properties: 'never'}],
      curly: 'error',
      'dot-notation': 'error',
      eqeqeq: 'error',
      'no-delete-var': 'error',
      'no-duplicate-imports': 'error',
      'no-else-return': 'error',
      'no-extra-bind': 'error',
      'no-extra-boolean-cast': 'error',
      'no-extra-label': 'error',
      'no-global-assign': 'error',
      'no-invalid-this': 'error',
      'no-labels': 'error',
      'no-lonely-if': 'error',
      'no-multi-str': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-template-curly-in-string': 'error',
      'no-throw-literal': 'error',
      'no-undef-init': 'error',
      'no-undefined': 'error',
      'no-unneeded-ternary': 'error',
      'no-unreachable-loop': 'error',
      'no-unused-expressions': 'error',
      'no-unused-vars': ['error', {caughtErrors: 'none', argsIgnorePattern: '^_'}],
      'no-use-before-define': ['error', {variables: false}],
      'no-useless-assignment': 'error',
      'no-useless-call': 'error',
      'no-useless-catch': 'error',
      'no-useless-concat': 'error',
      'no-useless-constructor': 'error',
      'no-useless-return': 'error',
      'no-var': 'error',
      'no-with': 'error',
      'one-var': ['error', 'never'],
      'prefer-arrow-callback': 'error',
      'prefer-const': 'error',
      'prefer-exponentiation-operator': 'error',
      'prefer-object-spread': 'error',
      'prefer-regex-literals': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'require-atomic-updates': 'error',
      'require-await': 'error'
    }
  },
  {
    files: ['test/**/*.js'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.mocha,
        ...globals.node,
        process: true,
        Buffer: true,
        global: true
      }
    },
    rules: {
      'no-undefined': 'off',
      'prefer-arrow-callback': 'off',
      'no-unused-expressions': 'off',
      'require-await': 'off',
      'one-var': 'off',
      'no-unused-vars': 'off',
      'prefer-exponentiation-operator': 'off',
      'curly': 'off',
      'arrow-body-style': 'off',
      'no-use-before-define': 'off',
      'array-callback-return': 'off',
      'camelcase': 'off',
      'dot-notation': 'off',
      'eqeqeq': 'off',
      'no-delete-var': 'off',
      'no-duplicate-imports': 'off',
      'no-else-return': 'off',
      'no-extra-bind': 'off',
      'no-extra-boolean-cast': 'off',
      'no-extra-label': 'off',
      'no-global-assign': 'off',
      'no-invalid-this': 'off',
      'no-labels': 'off',
      'no-lonely-if': 'off',
      'no-multi-str': 'off',
      'no-self-compare': 'off',
      'no-sequences': 'off',
      'no-template-curly-in-string': 'off',
      'no-throw-literal': 'off',
      'no-undef-init': 'off',
      'no-unneeded-ternary': 'off',
      'no-unreachable-loop': 'off',
      'no-useless-assignment': 'off',
      'no-useless-call': 'off',
      'no-useless-catch': 'off',
      'no-useless-concat': 'off',
      'no-useless-constructor': 'off',
      'no-useless-return': 'off',
      'no-var': 'off',
      'no-with': 'off',
      'prefer-const': 'off',
      'prefer-object-spread': 'off',
      'prefer-regex-literals': 'off',
      'prefer-rest-params': 'off',
      'prefer-spread': 'off',
      'require-atomic-updates': 'off'
    }
  }
]
