# Jekyll configuration for GitHub Pages
# This file configures how GitHub Pages serves the DozedEnt game

# Basic site settings
title: "DozedEnt - P2P Survival Game"
description: "WebAssembly-first multiplayer survival game with advanced AI, 5-button combat system, and serverless P2P networking"
baseurl: "/DozedEnt" # Repository name for GitHub Pages
url: "" # Your custom domain or leave empty for github.io domain

# Build settings
theme: null # We're using custom HTML/CSS, so no Jekyll theme
plugins: []

# Exclude files from being served
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - README.md
  - package.json
  - package-lock.json

# Include specific files/folders for GitHub Pages
include:
  - index.html
  - js/
  - css/
  - wasm/
  - assets/
  - images/
  - favicon.ico

# Disable Jekyll processing for certain files to preserve WASM and JS modules
defaults:
  - scope:
      path: "*.wasm"
    values:
      layout: null
      sitemap: false
  - scope:
      path: "wasm/**/*.wasm"
    values:
      layout: null
      sitemap: false
  - scope:
      path: "*.js"
    values:
      layout: null
      sitemap: false
  - scope:
      path: "js/**/*.js"
    values:
      layout: null
      sitemap: false
  - scope:
      path: "js/**/*.mjs"
    values:
      layout: null
      sitemap: false
  - scope:
      path: "js/**/*.ts"
    values:
      layout: null
      sitemap: false
  - scope:
      path: "js/**/*.d.ts"
    values:
      layout: null
      sitemap: false
  - scope:
      path: "css/**/*.css"
    values:
      layout: null
      sitemap: false
  - scope:
      path: "assets/**/*"
    values:
      layout: null
      sitemap: false

# MIME type configuration for WebAssembly
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
    'Access-Control-Allow-Methods': 'GET'
  mime_types:
    wasm: application/wasm

# GitHub Pages specific settings
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
